// <auto-generated />
using System;
using EnergyTrackerr.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyTrackerr.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511175438_UpdateSiteFields")]
    partial class UpdateSiteFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnergyTrackerr.Models.Alertes", b =>
                {
                    b.Property<int>("IdAlerte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerte"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EnergieId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipementId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Seuil")
                        .HasColumnType("float");

                    b.Property<string>("Severite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Traite")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAlerte");

                    b.HasIndex("EnergieId");

                    b.HasIndex("EquipementId");

                    b.ToTable("Alertes");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.AnalyseEnergetique", b =>
                {
                    b.Property<int>("IdAnalyse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnalyse"));

                    b.Property<int?>("AlerteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAnalyse")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resultat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeAnalyse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("IdAnalyse");

                    b.HasIndex("AlerteId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Anomalie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDetection")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MesureId")
                        .HasColumnType("int");

                    b.Property<bool>("Resolu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MesureId");

                    b.ToTable("Anomalies");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Energie", b =>
                {
                    b.Property<int>("IdEnergie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnergie"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnergieType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEnergie");

                    b.ToTable("Energies");

                    b.HasDiscriminator<string>("EnergieType").HasValue("Energie");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Equipement", b =>
                {
                    b.Property<int>("IdEquipement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipement"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateInstallation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateMiseEnService")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnergieId")
                        .HasColumnType("int");

                    b.Property<string>("Localisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Puissance")
                        .HasColumnType("float");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeEquipement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("IdEquipement");

                    b.HasIndex("EnergieId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Equipements");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Rapport", b =>
                {
                    b.Property<int>("IdRapport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRapport"));

                    b.Property<int?>("AnalyseId")
                        .HasColumnType("int");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("IdRapport");

                    b.HasIndex("AnalyseId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Rapports");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Recommandation", b =>
                {
                    b.Property<int>("IdRecommandation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecommandation"));

                    b.Property<int?>("AlerteId")
                        .HasColumnType("int");

                    b.Property<int?>("AnalyseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("IdRecommandation");

                    b.HasIndex("AlerteId");

                    b.HasIndex("AnalyseId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Recommandations");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Seuil", b =>
                {
                    b.Property<int>("IdSeuil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeuil"));

                    b.Property<int>("EnergieId")
                        .HasColumnType("int");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Valeur")
                        .HasColumnType("float");

                    b.HasKey("IdSeuil");

                    b.HasIndex("EnergieId");

                    b.ToTable("Seuils");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Site", b =>
                {
                    b.Property<int>("IdSite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSite"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSite");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Mesure", b =>
                {
                    b.Property<int>("IdMesure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMesure"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateMesure")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnergieId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipementId")
                        .HasColumnType("int");

                    b.Property<string>("SourceDonnee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Valeur")
                        .HasColumnType("float");

                    b.HasKey("IdMesure");

                    b.HasIndex("EnergieId");

                    b.HasIndex("EquipementId");

                    b.ToTable("Mesures");
                });

            modelBuilder.Entity("Notfication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Zone", b =>
                {
                    b.Property<int>("IdZone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZone"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("IdZone");

                    b.HasIndex("SiteId");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Eau", b =>
                {
                    b.HasBaseType("EnergyTrackerr.Models.Energie");

                    b.Property<double>("Debit")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Eau");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Electricite", b =>
                {
                    b.HasBaseType("EnergyTrackerr.Models.Energie");

                    b.Property<double>("Puissance")
                        .HasColumnType("float");

                    b.Property<double>("Tension")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Electricite");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Gasoil", b =>
                {
                    b.HasBaseType("EnergyTrackerr.Models.Energie");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Gasoil");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Alertes", b =>
                {
                    b.HasOne("EnergyTrackerr.Models.Energie", "Energie")
                        .WithMany()
                        .HasForeignKey("EnergieId");

                    b.HasOne("EnergyTrackerr.Models.Equipement", "Equipement")
                        .WithMany("Alertes")
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Energie");

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.AnalyseEnergetique", b =>
                {
                    b.HasOne("EnergyTrackerr.Models.Alertes", "Alerte")
                        .WithMany()
                        .HasForeignKey("AlerteId");

                    b.HasOne("EnergyTrackerr.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("Alerte");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Anomalie", b =>
                {
                    b.HasOne("Mesure", "Mesure")
                        .WithMany()
                        .HasForeignKey("MesureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesure");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Equipement", b =>
                {
                    b.HasOne("EnergyTrackerr.Models.Energie", "Energie")
                        .WithMany()
                        .HasForeignKey("EnergieId");

                    b.HasOne("Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.Navigation("Energie");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Rapport", b =>
                {
                    b.HasOne("EnergyTrackerr.Models.AnalyseEnergetique", "Analyse")
                        .WithMany()
                        .HasForeignKey("AnalyseId");

                    b.HasOne("EnergyTrackerr.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("Analyse");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Recommandation", b =>
                {
                    b.HasOne("EnergyTrackerr.Models.Alertes", "Alerte")
                        .WithMany()
                        .HasForeignKey("AlerteId");

                    b.HasOne("EnergyTrackerr.Models.AnalyseEnergetique", "Analyse")
                        .WithMany()
                        .HasForeignKey("AnalyseId");

                    b.HasOne("EnergyTrackerr.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("Alerte");

                    b.Navigation("Analyse");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Seuil", b =>
                {
                    b.HasOne("EnergyTrackerr.Models.Energie", "Energie")
                        .WithMany()
                        .HasForeignKey("EnergieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Energie");
                });

            modelBuilder.Entity("Mesure", b =>
                {
                    b.HasOne("EnergyTrackerr.Models.Energie", "Energie")
                        .WithMany("Mesures")
                        .HasForeignKey("EnergieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnergyTrackerr.Models.Equipement", "Equipement")
                        .WithMany("Mesures")
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Energie");

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("Notfication", b =>
                {
                    b.HasOne("EnergyTrackerr.Models.Utilisateur", "Utilisateur")
                        .WithMany("Notifications")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Zone", b =>
                {
                    b.HasOne("EnergyTrackerr.Models.Site", "Site")
                        .WithMany("Zones")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Energie", b =>
                {
                    b.Navigation("Mesures");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Equipement", b =>
                {
                    b.Navigation("Alertes");

                    b.Navigation("Mesures");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Site", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("EnergyTrackerr.Models.Utilisateur", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
